import {mkdir,writeFile,readFile} from 'node:fs/promises';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
let sharp;
try {sharp=require('sharp');} catch {sharp=require('C:/Users/roger/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/sharp');}
const out='dist/brand';await mkdir(out,{recursive:true});
const ink='#eeeae0',amber='#dbb37d',bg='#101211';
// An open A / play aperture and a separate orbital stroke. All mark geometry is editable.
const symbol=`<path d="M25 75 49 22Q50 20 51 22L75 75M35 55h29" fill="none" stroke="${ink}" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/><path d="M16 48C-1 81 75 93 89 44" fill="none" stroke="${amber}" stroke-width="2.5" stroke-linecap="round"/><path d="m47 42 14 10-14 10Z" fill="${amber}"/><circle cx="88" cy="31" r="4" fill="${amber}"/>`;
const svg=(w,h,body,view=`0 0 ${w} ${h}`)=>`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="${view}">${body}</svg>`;
const mark=svg(100,100,symbol);
await writeFile('dist/mark.svg',mark);await writeFile(`${out}/asitube-mark.svg`,mark);
await writeFile(`${out}/asitube-logo.svg`,svg(640,140,`<g transform="translate(0 8) scale(1.15)">${symbol}</g><text x="142" y="94" font-family="Arial,Helvetica,sans-serif" font-size="76" letter-spacing="-3" fill="${ink}"><tspan font-weight="600">ASI</tspan><tspan>Tube</tspan><tspan fill="${amber}">.</tspan></text>`));
await sharp(Buffer.from(mark)).resize(800,800).png().toFile(`${out}/asitube-mark-transparent.png`);
const avatar=svg(800,800,`<defs><radialGradient id="v"><stop stop-color="#273022"/><stop offset="1" stop-color="${bg}"/></radialGradient></defs><rect width="800" height="800" fill="url(#v)"/><circle cx="400" cy="400" r="327" fill="none" stroke="#3b4233"/><g transform="translate(135 115) scale(5.3)">${symbol}</g>`);
await writeFile(`${out}/youtube-avatar.svg`,avatar);await sharp(Buffer.from(avatar)).png().toFile(`${out}/youtube-avatar-800.png`);
await sharp(Buffer.from(mark)).resize(150,150).png().toFile(`${out}/video-watermark-150.png`);
function globe(cx,cy,r){let paths='';for(let lat=-40;lat<=40;lat+=2){let path='';const phi=lat/44*Math.PI/2;for(let j=0;j<=180;j++){const t=j/180*Math.PI*2,wave=.022*Math.sin(t*5+phi*8)+.015*Math.cos(t*9-phi*5),rr=1+wave;const x=Math.cos(phi)*Math.cos(t)*rr,y=Math.sin(phi)*rr,z=Math.cos(phi)*Math.sin(t)*rr;const yy=y*Math.cos(.28)-z*Math.sin(.28);path+=`${j?'L':'M'}${(cx+x*r).toFixed(2)} ${(cy+yy*r).toFixed(2)} `;}paths+=`<path d="${path}" fill="none" stroke="${amber}" stroke-opacity=".38" stroke-width="1.2"/>`;}
return `<circle cx="${cx}" cy="${cy}" r="${r*1.6}" fill="url(#glow)"/><circle cx="${cx}" cy="${cy}" r="${r*.97}" fill="url(#sphere)"/>${paths}<g fill="none" stroke="#b7b085" stroke-width="1" opacity=".38"><ellipse cx="${cx}" cy="${cy}" rx="${r*1.35}" ry="${r*.44}" transform="rotate(-29 ${cx} ${cy})"/><ellipse cx="${cx}" cy="${cy}" rx="${r*1.25}" ry="${r*.5}" transform="rotate(40 ${cx} ${cy})"/></g><circle cx="${cx+r*1.12}" cy="${cy-r*.4}" r="4" fill="${ink}"/>`;}
const defs=`<defs><radialGradient id="sphere" cx="35%" cy="30%" r="75%"><stop stop-color="#555135"/><stop offset=".5" stop-color="#30351f"/><stop offset="1" stop-color="#11180e"/></radialGradient><radialGradient id="glow"><stop stop-color="#ab8842" stop-opacity=".16"/><stop offset="1" stop-color="#ab8842" stop-opacity="0"/></radialGradient></defs>`;
let stars='';for(let i=0;i<230;i++)stars+=`<circle cx="${i*7919%2560}" cy="${i*3571%1440}" r="${i%7===0?1.6:.7}" fill="#cec6a0" opacity="${.12+i%4*.065}"/>`;
const bannerBody=`${defs}<rect width="2560" height="1440" fill="${bg}"/>${stars}${globe(1930,710,315)}<g transform="translate(632 603) scale(1.85)">${symbol}</g><text x="853" y="619" font-family="Arial,sans-serif" font-size="17" letter-spacing="4.5" fill="#a4ad97">A NEW KIND OF SCREEN</text><text x="850" y="731" font-family="Arial,Helvetica,sans-serif" font-size="116" letter-spacing="-5" fill="${ink}"><tspan font-weight="600">ASI</tspan><tspan>Tube</tspan><tspan fill="${amber}">.</tspan></text><text x="854" y="786" font-family="Georgia,serif" font-size="33" font-style="italic" fill="${amber}">Worlds become stories.</text><text x="854" y="834" font-family="Arial,sans-serif" font-size="16" letter-spacing="2.4" fill="#a6ad9b">SIMULATED WORLDS · AI STUDIOS · BRANCHING STORIES</text>`;
const banner=svg(2560,1440,bannerBody);await writeFile(`${out}/youtube-banner.svg`,banner);await sharp(Buffer.from(banner)).png().toFile(`${out}/youtube-banner-2560x1440.png`);
// The mobile-safe preview is a separate SVG viewport; the upload artwork contains no guides.
const mobile=svg(1545,423,bannerBody,'507.5 508.5 1545 423');await sharp(Buffer.from(mobile)).png().toFile(`${out}/youtube-banner-mobile-preview.png`);
const social=svg(1200,630,`${defs}<rect width="1200" height="630" fill="${bg}"/>${globe(900,300,185)}<g transform="translate(65 73) scale(.68)">${symbol}</g><text x="151" y="123" font-family="Arial,sans-serif" font-size="37" fill="${ink}">ASITube<tspan fill="${amber}">.</tspan></text><text x="80" y="290" font-family="Georgia,serif" font-size="72" fill="${ink}">Worlds become</text><text x="80" y="371" font-family="Georgia,serif" font-size="83" font-style="italic" fill="${amber}">stories.</text><text x="84" y="452" font-family="Arial,sans-serif" font-size="19" fill="#adb59f">Simulated worlds. AI studios. Branching stories.</text><text x="84" y="548" font-family="Arial,sans-serif" font-size="14" letter-spacing="3" fill="#9ea793">ASITUBE.COM</text>`);
await writeFile(`${out}/social-card.svg`,social);await sharp(Buffer.from(social)).png().toFile(`${out}/social-card-1200x630.png`);
console.log('Exported SVG masters, 2560 × 1440 banner, safe-area preview, 800px avatar, 150px watermark, and social card.');
